utils::globalVariables(c("guid",
                         "datum_wijziging",
                         "begin_geldigheid",
                         "eind_geldigheid",
                         "kolommen",
                         "domeintabel",
                         ".",
                         "domeintabelsoort",
                         "Begin geldigheid",
                         "Eind geldigheid",
                         "Elementtype ",
                         "Metadata ",
                         "Voorkeurslabel",
                         "Wijzigingsdatum",
                         "X1",
                         "wijzigingsdatum",
                         "Metadata",
                         "Elementtype",
                         "lower"))
